markdown:         rdiscount
pygments:         true
paginate:         5

title:            TBao
url:              http://timbao.github.io
feed:             /atom.xml
author:
    name:         Tim
    email:        dabao0521@gmail.com
    description:  "This is my blob built by github pages."

about:            "The one theme is another web theme design by PIZn."
follow:
    email:        dabao0521@gmail.com
    github:       https://github.com/TimBao
    twitter:      http://www.twitter.com/piznlin
    google:       https://plus.google.com/110733701770280812098
    facebook:     http://facebook.com/zhanxinlin
description:      Just another blog theme -- the One

indexContent:     false

style:            ./css/style.css
blogName:         TBao
blogDesc:         TimBao's blog
favicon:          /favicon.ico
theme:            default

disqus:           Tim Blog

copyright:        Copyright © 2014-2015 Tim All rights reserved.
test:             ok
